#!/bin/bash

run_location=$1
sim_dir=$2
min=$3
max=$4
nbeams=$5
num_openmp=$6
npert=$7
homedir=$(pwd)

echo "Running example "$min" to "$max" with mpi_procs="$nbeams" and openmp_threads="$num_openmp" per proc"
export OMP_NUM_THREADS=$num_openmp

for i in $(seq $min $max)
do
    for ipert in $(seq 0 $(($npert-1)))
    do
        echo "start: "$run_location$i$sim_dir$ipert
	cd $run_location$i$sim_dir$ipert
        chmod +x main
	#mpirun -np $nbeams ./main > a.out &
	./main > a.out
	cd $homedir
        echo "stop: "$run_location$i$sim_dir$ipert
    done
done

wait
